version: '3.8'

services:
  postgresqldb:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hungry_hub
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  app:
    container_name: hungry-hub
    depends_on:
      - postgresqldb
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    restart: always
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
    command: [sh, -c, 'npm run start:dev']

volumes:
  pgdata:
  node_modules: